name: Fix whitespace

on:
  push:
    branches:
    - "main"
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: sh

jobs:
  whitespace:
    name: "Fix whitespace"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download fix-whitespace
        run: |
          curl -L -o fix-whitespace https://github.com/agda/fix-whitespace/releases/download/v0.1/fix-whitespace-0.1-linux.binary
          chmod a+x fix-whitespace

      - name: Check whitespace
        run: |
          export PATH="$PWD:$PATH"
          CHECK=true ./scripts/format-fix-whitespace.sh
